parameters:
    eyja_rest.default_limit: 200

services:
    eyja_rest.listener.view:
        class: Eyja\RestBundle\EventListener\ViewListener
        arguments: [@eyja_rest.serializer]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    eyja_rest.listener.controller:
        class: Eyja\RestBundle\EventListener\ControllerListener
        arguments: [@eyja_rest.serializer]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    eyja_rest.listener.exception:
        class: Eyja\RestBundle\EventListener\ExceptionListener
        arguments: [@eyja_rest.serializer, %kernel.debug%]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }


    eyja_rest.serializer:
        class: Eyja\RestBundle\Serializer\Serializer
        arguments: [@jms_serializer]

    eyja_rest.serializer.query_deserialization_visitor:
        class: Eyja\RestBundle\Serializer\QueryDeserializationVisitor
        arguments: [@jms_serializer.naming_strategy, @jms_serializer.object_constructor]
        tags:
            - { name: jms_serializer.deserialization_visitor, format: query }


    eyja_rest.routing.loader:
        class: Eyja\RestBundle\Routing\RestLoader
        arguments: [@service_container]
        calls:
            - [setResolver, [ @routing.resolver ]]
        tags:
            - { name: routing.loader }

    eyja_rest.routing.collector:
        class: Doctrine\Common\Collections\ArrayCollection

    eyja_rest.metadata:
        class: Eyja\RestBundle\Utils\RestResourceMetadata
        arguments: [@service_container]