Eyja\RestBundle\Message\Collection:
    xml_root_name: response
    properties:
        results:
            type: array
            groups: [collection]
        metadata:
            type: array
            groups: [collection]
            xml_key_value_pairs: true
